runs:
  using: "composite"
  steps:
    - name: Install mockgen
      shell: bash
      run: go install github.com/golang/mock/mockgen@latest
    - name: Install goimports
      shell: bash
      run: go install golang.org/x/tools/cmd/goimports@latest
